apiVersion: v1
kind: DeploymentConfig
metadata:
  name: flask-demo
  labels:
    app: flask-demo
    service: flask-demo
spec:
  replicas: 1
  selector:
    deploymentconfig: flask-demo
  template:
    metadata:
      labels:
        app: flask-demo
        deploymentconfig: flask-demo
    spec:
      containers:
      - name: flask-demo
        image: flask-demo:latest
        resources: {}
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - flask-demo
      from:
        kind: ImageStreamTag
        name: flask-demo:latest
        namespace: flask-demo
    type: ImageChange
