apiVersion: v1
kind: Service
metadata:
  name: flask-demo
  labels:
    app: flask-demo
    service: flask-demo
spec:
  ports:
    - name: web
      port: 5000
      targetPort: 5000
  selector:
    deploymentconfig: flask-demo
